products = [
    {
        'model': "Product",
        '_id': "1",
        'name': "Fortune Refined Rice Bran Oil 1 L",
        'image': "/images/fortune-rice-bran-oil.jpg",
        'description':
        "Fortune Refined Rice Bran Oil 1 L Rice Bran Oil is a special cooking oil extracted from the brown layer of brown rice which is called rice bran. This oil is also called as heart oil as it is a health-friendly oil. It instantly enhances the flavour of your food, giving it an aromatic taste. Buy Fortune Refined Rice Bran Oil online now.",
        'brand': "Fortune",
        'category': "Oil",
        'price': 174.0,
        'countInStock': 0,
        'rating': 1.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "2",
        'name': "Red Label Natural Care Tea 500 g (Carton)",
        'image': "/images/red-label-natural-care-tea-500-g.jpg",
        'description':
        "Red Label Natural Care Tea 500 g (Carton)Give yourself a dose of natural freshness dissolved into a cup of a warm, refreshing portion of tea. Buy Red Label Natural Care Tea online, which is a refined blend of handpicked tea leaves and other natural ingredients that are meant to revitalize your body and mind. Enriched with loads of vitamins and anti-oxidants, this tea helps to boost health and build immunity, making you stronger and better. Every cup of the tea you prepare will comprise of authentic taste and refreshing aroma that will awaken your spirits for sure.",
        'brand': "Red Label",
        'category': "Tea",
        'price': 275.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "3",
        'name': "Tetley Lemon & Honey Green Tea Bags 25 pcs",
        'image': "/images/tetley-lemon-honey-green-tea-bags-30-pcs.jpg",
        'description':
        "Tetley Lemon & Honey Green Tea Bags 25 pcs Take a quick tea break with Tetley Lemon & Honey Green Tea. Apart from being a healthy option, the combination of lemon and honey leaves you feeling energized. The ingredients for each teabag have been procured carefully and the packaging ensures these bags remain fresh over a period of time. So go ahead, buy Tetley Lemon & Honey Green Tea Bags online today!How to use:Bring fresh water to boil.",
        'brand': "TETLEY",
        'category': "Tea",
        'price': 140.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "4",
        'name': "India Gate Feast Rozzana Basmati Rice 5 kg INDIA GATE",
        'image': "/images/india-gate-feast-rozzana-basmati-rice-5-kg.jpg",
        'description':
        "India Gate Feast Rozzana Basmati Rice is everyday rice that makes each meal memorable. It is ideal for people who like to include rice in their daily meal consumption. Aromatic, flavourful, and defined by its distinctly long and slender grains, India Gate Feast Rozzana Basmati Rice turns every meal into comfort food. No matter what you’re in the mood for, India Gate Feast Rozzana Basmati Rice leaves you feeling satisfied and nourished. Buy India Gate Feast Rozzana Basmati Rice online today.",
        'brand': "INDIA GATE",
        'category': "Rice",
        'price': 339.0,
        'countInStock': 10,
        'rating': 3.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "5",
        'name': "India Gate Feast Rozzana Basmati Rice 1 kg INDIA GATE",
        'image': "/images/india-gate-feast-rozzana-basmati-rice-1-kg.jpg",
        'description':
        "India Gate Feast Rozzana Basmati Rice is everyday rice that makes each meal memorable. It is ideal for people who like to include rice in their daily meal consumption. Aromatic, flavourful, and defined by its distinctly long and slender grains, India Gate Feast Rozzana Basmati Rice turns every meal into comfort food. No matter what you’re in the mood for, India Gate Feast Rozzana Basmati Rice leaves you feeling satisfied and nourished. Buy India Gate Feast Rozzana Basmati Rice online today.",
        'brand': "INDIA GATE",
        'category': "Rice",
        'price': 74.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "6",
        'name': "Varalakshmi Premium Sabudana / Sago 1 kg",
        'image': "/images/varalakshmi-premium-sabudana-sago-1-kg.jpg",
        'description':
        "Varalakshmi Premium Sabudana / Sago 1 kg Varalakshmi Premium Sabudana / Sago is the most commonly used food during fasting. It is a good source of Energy and Carbohydrates. It can fulfil the nutritional and dietary requirements during the fast. Buy Varalakshmi Premium Sabudana / Sago online now!",
        'brand': "VARALAKSHMI",
        'category': "Rice",
        'price': 80.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "7",
        'name': "Varalakshmi Premium Sabudana / Sago 500 g",
        'image': "/images/varalakshmi-premium-sabudana-sago-1-kg.jpg",
        'description':
        "Varalakshmi Premium Sabudana / Sago 500 g Varalakshmi Premium Sabudana / Sago is the most commonly used food during fasting. It is a good source of Energy and Carbohydrates. It can fulfil the nutritional and dietary requirements during the fast. Buy Varalakshmi Premium Sabudana / Sago online now!",
        'brand': "VARALAKSHMI",
        'category': "Rice",
        'price': 45.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "8",
        'name': "Aashirvaad Whole Wheat Atta 10 kg",
        'image': "/images/aashirvaad-whole-wheat-atta-10-kg.jpg",
        'description':
        "Aashirvaad Whole Wheat Atta provides the goodness of health in every bite. This product incorporates many benefits of wheat and lets your body maintain a nutrient balance. It is made of nutritious wheat grains. Also, it has a sweet taste that gives you fuller and softer rotis, every single time. Buy Aashirvaad Whole Wheat Atta online now.",
        'category': "Atta",
        'price': 375.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "9",
        'name': "Aashirvaad Whole Wheat Atta 5 kg",
        'image': "/images/aashirvaad-whole-wheat-atta-10-kg.jpg",
        'description':
        "Aashirvaad Whole Wheat Atta provides the goodness of health in every bite. This product incorporates many benefits of wheat and lets your body maintain a nutrient balance. It is made of nutritious wheat grains. Also, it has a sweet taste that gives you fuller and softer rotis, every single time. Buy Aashirvaad Whole Wheat Atta online now.",
        'category': "Atta",
        'price': 210.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "10",
        'name': "Rashi Organic Sugar 1 kg",
        'image': "/images/rashi-organic-sugar-500-g.jpg",
        'description':
        "Rashi Organic Sugar 1 kg Rashi Organic Sugar is darker in colour and stickier in texture and has a definite caramel taste. It is a soft, lumpy product which is richer in molasses when compared to raw sugar. This contains 3 percent protein, small amounts of minerals like calcium, phosphorous, magnesium and Sulphur, trace elements such as copper, iron, manganese and zinc and B-vitamins, even good sugars should be consumed within healthy limits. Buy Rashi Organic Sugar online now.",
        'category': "SUGAR",
        'price': 88.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "11",
        'name': "Good Life Almonds 200 g",
        'image': "/images/good-life-almonds-200-g.jpg",
        'description':
        "Good Life Almonds are a profoundly nutritional nut and a rich source of Vitamin E, Calcium, Phosphorus, Iron, and Magnesium. Compared to all other nuts, they are rich in nutrients which helps in the overall healthy development. Buy Good Life Almonds online now!",
        'category': "DRY FRUITS",
        'price': 88.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "12",
        'name': "Sapphero Unshelled Walnuts 200 g",
        'image': "/images/sapphero-unshelled-walnuts-200-g.jpg",
        'description':
        "Sapphero Unshelled Walnuts are a perfect package of Proteins, essential Fatty Acids, Antioxidants, Fibre, Vitamins And Minerals. It is an excellent source of Omega-3 Fatty Acids. No wonder walnuts are a favourite among snacks. Buy Sapphero Unshelled Walnuts online now.",
        'category': "DRY FRUITS",
        'price': 499.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "13",
        'name': "Sapphero Jardalu / Apricots 250 g",
        'image': "/images/sapphero-jardalu-apricots-250-g.jpg",
        'description':
        "Sapphero Jardalu / Apricots 250 g Apricots are the finest dry fruits that are nutritious and delicious. They contain many health benefits by improving the immune system, eyes and promotes healthy skin. They are packed with essential minerals as well. Sapphero Jardalu / Apricots is processed, cleaned and packaged by industry professionals preserving the natural nutrient content. Buy Sapphero Jardalu / Apricots online now",
        'category': "DRY FRUITS",
        'price': 289.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "14",
        'name': "Sapphero Hazelnuts 250 g",
        'image': "/images/sapphero-hazelnuts-250-g.jpg",
        'description':
        "Sapphero Hazelnuts 250 g Hazelnut can be consumed on daily basis. Delay premature ageing, keeps you safe from harsh UV ray, keeps your skin hydrated. They are an amazing treat option for sudden hunger pangs. These hazelnuts are sweet with a nutty aroma. Buy Sapphero Hazelnuts online now!",
        'category': "DRY FRUITS",
        'price': 389.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "15",
        'name': "Sapphero Roasted & Salted Pistachios 250 g",
        'image': "/images/sapphero-roasted-salted-pistachios-250-g.jpg",
        'description':
        "Sapphero Roasted & Salted Pistachios 250 g Add Sapphero Roasted and Salted Pistachios to your daily diet routine for good health and enjoy a flavorful snack. Sapphero Roasted and Salted Pistachios have a lot of nutritional benefits. It contains healthy Fats, Fibre, Protein and Antioxidants making it the best snack choice. Buy Sapphero Roasted and Salted Pistachios online now!",
        'category': "DRY FRUITS",
        'price': 425.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "16",
        'name': "Sapphero Dry Blueberries 250 g",
        'image': "/images/sapphero-dry-blueberries-250-g.jpg",
        'description':
        "Sapphero Dry Blueberries 250 g Sapphero Dry Blueberries are packed with antioxidants and vitamins for a healthy treat. These dried blueberries are slightly sweetened and ideal for mixing in cereals or adding to cakes and muffins. They also make a delicious addition to salads and are perfect for snacking on. One taste of these plump and sweet dried blueberries and your taste buds will be in paradise. Buy Sapphero Dry Blueberries online now!",
        'category': "DRY FRUITS",
        'price': 499.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "17",
        'name': "Good Life Urad Dal 500 g",
        'image': "/images/good-life-urad-dal-500-g.jpg",
        'description':
        "Good Life Urad Dal 500 g Good Life Urad Dal has immeasurable benefits. It has constituted an important part of Indian cuisine. It can fulfil the nutritional and dietary requirements of an entire meal. It has various positive impacts on one's health and body. Buy Good Life Urad Dal online now!",
        'category': "DAL",
        'price': 60.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "18",
        'name': "Good Life Urad Dal 1 Kg",
        'image': "/images/good-life-urad-dal-500-g.jpg",
        'description':
        "Good Life Urad Dal 1 kg  Good Life Urad Dal has immeasurable benefits. It has constituted an important part of Indian cuisine. It can fulfil the nutritional and dietary requirements of an entire meal. It has various positive impacts on one's health and body. Buy Good Life Urad Dal online now!",
        'category': "DAL",
        'price': 140.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "19",
        'name': "Amul Butter 500 g (Carton)",
        'image': "/images/amul-butter-500-g-carton.jpg",
        'description':
        "Amul Butter 500 g (Carton)Who doesnt like a chunk of creamy, velvety, smooth and mouth-watering butter? Made with fresh ingredients, Amul Butter is a multi-purpose butter that can be used as a spread on bread, paratha, roti, naan and sandwiches. It also makes an excellent topping for Pav-bhaji, dal, soups, salads, rice as well as a great cooking medium for Paneer Butter Masala, Dal Makhni and a variety of delightful recipes. So what are you waiting for? Buy this product online today!",
        'category': "DAIRY",
        'price': 225.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "20",
        'name': "Amul Butter 500 g (Carton)",
        'image': "/images/amul-butter-100-g-carton.jpg",
        'description':
        "Amul Butter 500 g (Carton)Who doesnt like a chunk of creamy, velvety, smooth and mouth-watering butter? Made with fresh ingredients, Amul Butter is a multi-purpose butter that can be used as a spread on bread, paratha, roti, naan and sandwiches. It also makes an excellent topping for Pav-bhaji, dal, soups, salads, rice as well as a great cooking medium for Paneer Butter Masala, Dal Makhni and a variety of delightful recipes. So what are you waiting for? Buy this product online today!",
        'category': "DAIRY",
        'price': 60.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "21",
        'name': "Amulya Dairy Whitener 500 g (Pouch)",
        'image': "/images/amulya-dairy-whitener-500-g.jpg",
        'description':
        "Amulya Dairy Whitener 500 g (Pouch)There  no greater joy than finding a milk powder that works as a healthy substitute for milk with zero compromises in the natural taste. Amulya Dairy Whitener made from wholesome milk adds the right texture and taste to your tea, cakes, cookies, sweets, and smoothies. Buy this product online today.",
        'category': "DAIRY",
        'price': 160.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "22",
        'name': "Nestle EveryDay Dairy Whitener 200 g (Pouch)",
        'image': "/images/nestle-everyday-dairy-whitener-200-g.jpg",
        'description':
        "Nestle EveryDay Dairy Whitener 200 g (Pouch) There is no greater joy than finding a milk powder that works as a healthy substitute for milk with zero compromises in the natural taste. Nestle EveryDay Dairy Whitener made from wholesome milk adds the right texture and taste to your tea, cakes, cookies, sweets, and smoothies. Buy this product online today.",
        'category': "DAIRY",
        'price': 100.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "23",
        'name': "Everest Coriander Powder 100 g",
        'image': "/images/everest-coriander-powder-100-g.jpg",
        'description':
        "Everest Coriander Powder 100 g Coriander powder is one of the most important ingredients of every Indian cuisine. Add a tablespoon of Everest Coriander Powder to enhance the flavour and aroma of your vegetarian and non-vegetarian dish. Give your delicacies a distinctive taste, buy this product online today.",
        'category': "MASALA",
        'price': 25.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "24",
        'name': "Everest Tikhalal Chilli Powder 500 g",
        'image': "/images/everest-tikhalal-chilli-powder-500-g.jpg",
        'description':
        "Everest Tikhalal Chilli Powder 500 g Do you know what gives colour to your Dum Aloo? Do you know what turns your ordinary street-food and snacks on the plate spicy and delicious! It Is none other than the humble Chilli Powder. Add a teaspoon of Everest Tikhalal Chilli Powder to your homemade khichdi, bhaji, chutney, veg and non-veg curries or sprinkle on your chaat, dosa and dahi vada for a hot and spicy twist. Buy this product online today.",
        'category': "MASALA",
        'price': 198.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "25",
        'name': "Smith & Jones Ginger Garlic Paste 200 g",
        'image': "/images/smith-jones-ginger-garlic-paste-200-g.jpg",
        'description':
        "Smith & Jones Ginger Garlic Paste 200 g Smith & Jones Ginger Garlic Paste is a curry-base composed of the strong, sweet flavour of garlic combined with the biting taste of ginger. It's ready-to-use with zero compromises in the aroma and taste that is usually expected from homemade ginger-garlic pastes. Buy this product online today.",
        'category': "MASALA",
        'price': 40.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "26",
        'name': "Catch Chatpata Chat Masala 100 g",
        'image': "/images/catch-chatpata-chat-masala-100-g.jpg",
        'description':
        "Catch Chatpata Chat Masala 100 g Chaat is the best form of Indian street food that brings you a profusion of flavours from sweet and tangy to everything in between. One of the staples used in all kinds of street food is a spice mix known as chat masala. Catch Chatpata Chat Masala is the perfect additive to lift the taste of any kind of street food. Buy this product online today.",
        'category': "MASALA",
        'price': 50.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "27",
        'name': "Catch Shahi Paneer Masala 100 g",
        'image': "/images/catch-shahi-paneer-masala-100-g.jpg",
        'description':
        "Catch Shahi Paneer Masala 100 g Shahi paneer masala is a very well known spice mix for Indian cheese curry meal. Follow the easy to cook instructions offered on the back of the box for a luscious dish that your whole family will enjoy. Dissolve with cream on top. Buy Catch Shahi Paneer Masala online today.",
        'category': "MASALA",
        'price': 60.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'model': "Product",
        '_id': "28",
        'name': "Catch Garam Masala 100 g",
        'image': "/images/catch-garam-masala-100-g.jpg",
        'description':
        "Catch Garam Masala 100 g Using Garam Masala in Indian cooking is a trend that is followed since ages. Garam Masala is acclaimed for its aroma and flavour. Catch Garam Masala Powder is a unique assortment of traditional spices. Add it to your savoury veg and non-veg curry, lentils or sprinkle on your ordinary snacks for a delectable twist. Buy this product online now.",
        'category': "MASALA",
        'price': 60.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },

    {
        'model': "Product",
        '_id': "29",
        'name': "JK Poppy Seeds 100 g",
        'image': "/images/jk-poppy-seeds-100-g.jpg",
        'description':
        "JK Poppy Seeds 100 g Poppy Seeds are commonly called as Khas Khas. They are used in whole or ground form in various recipes. Use JK Poppy Seeds in cakes, rusk and muffins to give them an exotic taste. Buy this product online today.",
        'category': "MASALA",
        'price': 190.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },

    {
        'model': "Product",
        '_id': "30",
        'name': "Catch Kitchen King Masala 100 g",
        'image': "/images/catch-kitchen-king-masala-100-g.jpg",
        'description':
        "Catch Kitchen King Masala 100 g Catch Kitchen King Masala is made from fresh and select variety of whole spices that are ground to perfection. Add a teaspoon of this masala to dal, vegetable dishes, meat and chicken curries to give them a flavourful twist. Buy this product online today.",
        'category': "MASALA",
        'price': 54.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },

    {
        'model': "Product",
        '_id': "31",
        'name': "Everest Chicken Masala 100 g",
        'image': "/images/everest-chicken-masala-100-g.jpg",
        'description':
        "Everest Chicken Masala 100 g Everest Chicken Masala is a spicy masala that gives you restaurant-style chicken dishes in minutes. It is a blend of fresh and aromatic spices that give your recipe that quintessential hue and irresistible aroma. Buy this product online today.",
        'category': "MASALA",
        'price': 65.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },

    {
        'model': "Product",
        '_id': "32",
        'name': "Everest Turmeric Powder 500 g",
        'image': "/images/everest-turmeric-powder-500-g.jpg",
        'description':
        "Everest Turmeric Powder 500 g Turmeric or Haldi is an essential ingredient in Indian cuisine. Everest Turmeric Powder is not only used for its flavour and aroma but also for its health benefits. It has antiseptic qualities as well as properties of flavouring agent and is also a natural beauty aid. It gives musky flavour and yellow colour to curries. Buy this product online today.",
        'category': "MASALA",
        'price': 121.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },

    {
        'model': "Product",
        '_id': "33",
        'name': "Everest Royal Garam Masala 100 g",
        'image': "/images/everest-royal-garam-masala-100-g.jpg",
        'description':
        "Everest Royal Garam Masala 100 g Using Garam Masala in Indian cooking is a trend that is followed since ages. Garam masala is acclaimed for its aroma and flavour. Everest Royal Garam Masala is a unique assortment of traditional spices. Add it to your savoury veg and non-veg curries for a flavourful twist. Buy this product online now.",
        'category': "MASALA",
        'price': 70.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },

    {
        'model': "Product",
        '_id': "34",
        'name': "Everest Pav Bhaji Masala 100 g",
        'image': "/images/everest-pav-bhaji-masala-100-g.jpg",
        'description':
        "Everest Pav Bhaji Masala 100 g Everest Pav Bhaji Masala is a special blend of spices used to prepare everyone's favourite street-snack, Pav Bhaji. Add a teaspoon of this masala to the mashed vegetables (bhaji) and serve with hot pavs (buns) with loads of extra butter. Buy this product online today.",
        'category': "MASALA",
        'price': 60.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },

    {
        'model': "Product",
        '_id': "35",
        'name': "Everest Chhole Masala 100 g",
        'image': "/images/everest-chhole-masala-100-g.jpg",
        'description':
        "Everest Chhole Masala 100 g Everest Chhole Masala is a ready-to-add masala that gives you restaurant-style chhole curry in minutes. Add a teaspoon of this powder to your gravy, garnish with fresh coriander and serve hot with bhature, paratha or steamed rice. Make tasty chhole curry at home, buy this product online today.",
        'category': "MASALA",
        'price': 54.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },

    {
        'model': "Product",
        '_id': "36",
        'name': "Tide Naturals Lemon & Chandan Detergent Powder 800 g",
        'image': "/images/tide-naturals-lemon-chandan-detergent-powder-800-g.jpg",
        'description':
        "Tide Naturals Lemon & Chandan Detergent Powder 800 g Now do not stop your kids from dirtying their clothes as Tide Naturals Lemon & Chandan Detergent Powder is here. This detergent provides outstanding whiteness to white clothes and retains the colour of non-white clothes with brilliant cleaning. It is packed with the benefits of lemon and sandalwood (Chandan) thus along with cleaning, it also keeps your hands soft. So go ahead and buy this product online today!",
        'category': "HOME CARE",
        'price': 55.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },

    {
        'model': "Product",
        '_id': "37",
        'name': "Surf Excel Easy Wash Detergent Powder 1 kg",
        'image': "/images/surf-excel-easy-wash-detergent-powder-1-kg.jpg",
        'description':
        "Surf Excel Easy Wash Detergent Powder 1 kgSurf Excel Easy Wash Detergent Powder is a superfine powder that removes tough stains in a jiffy and leaves no residue on your clothes. Being a superfine and fluffy powder, it dissolves easily and reaches the stain and removes it easily. Its engineered formula with a superior technology unleashes the power of 10 hands that is effective in removing the toughest of stains such as those of mud, ink, oil, ketchup, curry , and chocolate very easily. So go ahead and buy this product online today!",
        'category': "HOME CARE",
        'price': 110.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },

    {
        'model': "Product",
        '_id': "38",
        'name': "Ghadi Detergent Cake 160 g (Pack of 5)",
        'image': "/images/ghadi-detergent-cake-160-g-pack-of-5.jpg",
        'description':
        "Ghadi Detergent Cake 160 g (Pack of 5) Your whites will be whiter and the colours will be brighter with this Ghadi Detergent Cake. Known to remove the toughest stains, this detergent bar is gentle on hands & has a good fragrance. Keep your worries at bay with this powerful detergent bar, which shall make harsh stains, dirt, and grime disappear within seconds. So go ahead and buy this product online today!",
        'category': "HOME CARE",
        'price': 35.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },

    {
        'model': "Product",
        '_id': "39",
        'name': "Tide Big Detergent Bar 250 g",
        'image': "/images/tide-big-detergent-bar-250-g.jpg",
        'description':
        "Tide Big Detergent Bar 250 g Stains will no longer be a problem for you and your fabrics when you have Tide Big Detergent Bar. It makes sure that the stubborn stains are removed effectively while leaving a pleasant fragrance. It helps you to get rid of the grime, dirt as well as the germs on your clothes. So go ahead and buy this product online today!",
        'category': "HOME CARE",
        'price': 20.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },

    {
        'model': "Product",
        '_id': "40",
        'name': "Comfort After Wash Lily Fresh Fabric Conditioner 220 ml",
        'image':
        "/images/comfort-after-wash-lily-fresh-fabric-conditioner-220-ml.jpg",
        'description':
        "Comfort After Wash Lily Fresh Fabric Conditioner 220 ml Ensure your clothes retain their shine and colour, for a long time with each wash by using this Comfort After Wash Lily Fresh Fabric Conditioner. This fabric conditioner smoothens the tangled fibres while leaving them feeling soft and supple. It makes clothes soft, smooth and great to wear. So go ahead and buy this product online today!",
        'category': "HOME CARE",
        'price': 51.0,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
]
